config/routes.rb
Rails.application.routes.draw do
  # resources :posts, except: [:show]
  resources :posts, param: :id, path: '/id/', only: [:show]
  root to: 'posts#index'
  # devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action { @posts = Post.all.order(created_at: :desc).limit(12) }
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @title = 'Hive Color'
  end

  def show
    @title = @post.title
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta http-equiv="content-language" content="ja">
    <meta http-equiv="content-style-type" content="text/css">
    <meta http-equiv="content-script-type" content="text/javascript">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
    <meta name="keywords" content="ツイッター,ソーシャル">
    <meta name="description" content="最近ツイッターで見かけた面白い情報を書くブログ。">

    <link rel="icon" type="image/x-icon" href="/favicon.png">

    <%# stylesheet_link_tag '/cake_css/cake.generic.css', media: 'all' %>
    <%= stylesheet_link_tag '/cake_css/normal.css', media: 'all' %>

    <title><%= @title ? @title : 'Hive Color' %></title>
    <%= csrf_meta_tags %>

    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-13072051-6"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-13072051-6');
    </script>

    <script type="text/javascript" src="/cake_js/social_buttons.js"></script>

    <%# stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script data-ad-client="ca-pub-3146843071247817" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div id="fb-root"></div>
  <script>(function (d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.5&appId=900171283365563";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>

  <div id="layout">

    <div id="header">
      <h1>Hive Color</h1>
      <h2><a href="/">Hive Color</a></h2>
    </div>

    <div id="contents">
      <%= yield %>
    </div>

    <div id="right_side_float" style="">

      <div class="clear"></div>

      <div id="right_side" style="">

        <div id="author_info" class="box">
          <div id="author_title" class="box_title">著者プロフィール</div>
          <div id="author_detail" class="box_detail">
            Webサイトをいくつか作っています。
            <div style="text-align: center;">
              <div style="padding: 3px 0px 3px 0px;">
                <a href="https://twitter.com/ts_3156" target="_blank"><img src="/cake_img/profile.png" width="120" height="188" alt="著者プロフィール"></a>
              </div>
            </div>
            <div style="text-align: right; font-size: 10px;">
              <a href="https://twitter.com/ts_3156" target="_blank">ツイッターはこちら</a></div>
          </div><!-- author_detail -->
        </div><!-- author_info -->

        <div id="new_info" class="box">
          <div id="new_info_title" class="box_title">新着記事</div>
          <div id="new_info_detail" class="box_detail">
            <div>
              <%= render partial: 'posts/new_info', locals: {posts: @posts || []} %>
            </div>
            <div style="text-align: right; font-size: 10px;"><a href="/list">新しい記事一覧</a></div>
          </div><!-- new_info_detail -->
        </div><!-- new_info -->

        <div id="popular_info" class="box">
          <div id="popular_info_title" class="box_title">ソーシャルランキング</div>
          <div id="popular_info_detail" class="box_detail">
            <div>
              <div>・2013/05/30</div><p><a href="/id/103">Lean Analytics: KPIにしてはいけない8つの指標</a> <span style="color: #ff0000;">349 users</span></p>
              <div>・2011/12/20</div><p><a href="/id/19">楽天が大成功した理由とクラウドファンディングが成功しない理由</a> <span style="color: #ff0000;">174 users</span></p>
              <div>・2013/05/26</div><p><a href="/id/100">ニコニコ動画のタグの傾向を見てみた</a> <span style="color: #ff0000;">77 users</span></p>
              <div>・2013/05/28</div><p><a href="/id/101">ニコニコ動画のタグネットワークを描画してみた</a> <span style="color: #ff0000;">75 users</span></p>
              <div>・2012/11/25</div><p><a href="/id/37">fluentdの簡単な使い方、設定方法一覧</a> <span style="color: #ff0000;">65 users</span></p>
              <div>・2012/03/24</div><p><a href="/id/24">Android SDK r17で高速化されたAndroidエミュレータを動かす全手順</a> <span style="color: #ff0000;">59 users</span></p>
              <div>・2011/12/19</div><p><a href="/id/18">とんQに提案メールを送ったらすっごい丁寧な返事が返ってきた！</a> <span style="color: #ff0000;">42 users</span></p>
              <div>・2013/03/17</div><p><a href="/id/47">各種レコメンドアルゴリズムの特徴・計算方法まとめ</a> <span style="color: #ff0000;">35 users</span></p>
              <div>・2013/05/29</div><p><a href="/id/102">ABテストを検定する</a> <span style="color: #ff0000;">34 users</span></p>
              <div>・2013/03/14</div><p><a href="/id/43">Job Queueシステムを自分で設計するときに必要な設定項目メモ</a> <span style="color: #ff0000;">29 users</span></p>
              <div>・2013/03/14</div><p><a href="/id/43">Job Queueシステムを自分で設計するときに必要な設定項目メモ</a> <span style="color: #ff0000;">29 users</span></p>
            </div>
          </div><!-- popular_info_detail -->
        </div><!-- popular_info -->

        <div id="access_rank_info" class="box">
          <div id="access_rank_info_title" class="box_title">アクセス数ランキング</div>
          <div id="access_rank_info_detail" class="box_detail">
            <div>
              <div>・2012/01/07</div><p><a href="/id/21">Android端末のGoogleアカウント同期機能まとめ【電話帳、Gmail、カレンダー、Picasa】</a></p>
              <div>・2012/03/24</div><p><a href="/id/24">Android SDK r17で高速化されたAndroidエミュレータを動かす全手順</a></p>
              <div>・2012/10/14</div><p><a href="/id/28">HTMLだけでツイッターを埋め込む方法</a></p>
              <div>・2011/12/20</div><p><a href="/id/19">楽天が大成功した理由とクラウドファンディングが成功しない理由</a></p>
              <div>・2012/10/10</div><p><a href="/id/27">絵師さんが参考にしているサイト だいたい200個まとめ</a></p>
            </div>
          </div><!-- access_rank_info_detail -->
        </div><!-- access_rank_info -->

      </div><!-- right_side -->
    </div><!-- right_side_float -->

    <div class="clear"></div>

    <div id="footer">
      <div id="list">
        <a href="/">トップ</a> |
        <a href="https://twitter.com/ts_3156" target="_blank">お問い合わせ</a> |
        <a href="https://policies.google.com/technologies/partner-sites?hl=ja" target="_blank">広告表示ポリシー</a>
      </div>
      <div id="copy_right">&copy;2011-2011 Shinohara. All rights reserved.</div>
    </div><!-- footer -->

  </div><!-- layout -->

  </body>
</html>

app/views/posts/_each_social_buttons.html.erb
<table class="social_button_table" align="right"><tr>
  <td><div style="margin-left: 10px;"><a href="//twitter.com/share?text=<%= URI.escape(post.title) %>&amp;url=<%= "#{post_url(post)}" %>" target="_blank"><img src="/cake_img/social_buttons/tweet_button2.png" width="16" height="16" alt="ツイッターに投稿する"></a></div></td>
  <td><div style="margin-left: 2px;" class="tweet_count_<%= post.id %>"></div></td>

  <td><div style="margin-left: 10px;"><a href="//www.facebook.com/sharer.php?u=<%= "#{post_url(post)}" %>" target="_blank"><img src="/cake_img/social_buttons/fb_like_button2.png" width="16" height="16" alt="Facebookに投稿する"></a></div></td>
  <td><div style="margin-left: 2px;" class="fb_count_<%= post.id %>"></div></td>

  <td><div style="margin-left: 10px;"><a href="//b.hatena.ne.jp/add?mode=confirm&amp;url=<%= "#{post_url(post)}" %>" target="_blank"><img src="/cake_img/social_buttons/hatena.png" width="16" height="16" alt="はてなでブックマークする"></a></div></td>
  <td><div style="margin-left: 2px;" class="hatebu_count_<%= post.id %>"></div></td>
</tr></table>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_new_info.html.erb
<% posts.each.with_index do |post, i| %>
  <div>・<%= post.created_at.to_s(:new_info) %></div><p><a href="<%= post_path(post) %>"><%= post.title %></a> <% if i < 3 %><span style="color: #ff0000;">new</span><% end %></p>
<% end %>

app/views/posts/_social_buttons.html.erb
<table class="social_button_table" align="right"><tr>
  <td><div style="margin-left: 10px;"><a href="//twitter.com/share?text=<%= URI.escape(post.title) %>&amp;url=<%= "#{post_url(post)}" %>" target="_blank"><img src="/cake_img/social_buttons/tweet_button2.png" width="16" height="16" alt="ツイッターに投稿する"></a></div></td>
  <td><div style="margin-left: 2px;" class="tweet_count_<%= post.id %>"></div></td>

  <td><div style="margin-left: 10px;"><a href="//www.facebook.com/sharer.php?u=<%= "#{post_url(post)}" %>" target="_blank"><img src="/cake_img/social_buttons/fb_like_button2.png" width="16" height="16" alt="Facebookに投稿する"></a></div></td>
  <td><div style="margin-left: 2px;" class="fb_count_<%= post.id %>"></div></td>

  <td><div style="margin-left: 10px;"><a href="//b.hatena.ne.jp/add?mode=confirm&amp;url=<%= "#{post_url(post)}" %>" target="_blank"><img src="/cake_img/social_buttons/hatena.png" width="16" height="16" alt="はてなでブックマークする"></a></div></td>
  <td><div style="margin-left: 2px;" class="hatebu_count_<%= post.id %>"></div></td>
</tr></table>

app/views/posts/_summary.html.erb
<div class="each_post">
  <div style="position: relative;">
    <div style="position: absolute; top: 0px; right: 0px;">
      <%= render partial: 'posts/social_buttons', locals: {post: post} %>
    </div>
    <div style="position: absolute; top: 25px; right: 0px;">
      <div class="post_date"><%= post.created_at.to_s(:post_title) %></div>
    </div>
  </div>

  <div style="width: 520px; margin-bottom: 40px;">
    <h3 class="post_title"><a href="<%= post_path(post) %>"><%= post.title %></a></h3>
  </div>

  <div class="clear"></div>

  <div class="post_text" style="">
    <%= post.summary.html_safe %>
    <br><p><a href="<%= post_path(post) %>">続きを読む！</a></p>
  </div>

  <%= render partial: 'posts/social_buttons', locals: {post: post} %>

  <div class="clear"></div><%# これがないと下の要素にめり込む %>

  <script type="text/javascript">
      <!--
      likeCount('fb_count_<%= post.id %>', '<%= post_url(post) %>');
      // tweetCount('tweet_count_<%= post.id %>', '<%= post_url(post) %>');
      hatebuCount('hatebu_count_<%= post.id %>', '<%= post_url(post) %>');
      // -->
  </script>
</div><!-- each_post -->

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<%= render partial: 'posts/summary', collection: @posts, as: :post, cached: true %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="each_post">

  <div style="position: relative;">
    <div style="position: absolute; top: 0px; right: 0px;">
      <%= render partial: 'posts/social_buttons', locals: {post: @post} %>
    </div>
    <div style="position: absolute; top: 25px; right: 0px;">
      <div class="post_date"><%= @post.created_at.to_s(:post_title) %></div>
    </div>
  </div>

  <div style="width: 520px; margin-bottom: 40px;">
    <h3 class="post_title"><a href="<%= post_path(@post) %>"><%= @post.title %></a></h3>
  </div>

  <div class="clear"></div>

  <div class="post_text" style="">
    <%= (@post.summary + @post.body).html_safe %>
  </div>

  <%= render partial: 'posts/social_buttons', locals: {post: @post} %>

  <div class="clear"></div><%# これがないと下の要素にめり込む %>

  <div id="comment_by_facebook_wrapper"><%# これがない印刷時に非表示にできない %>
    <div style="border-width: 1px; border-style: solid; border-radius: 3px; margin-top: 10px; padding: 28px;" class="fb-comments comment_by_facebook" data-href="<%= post_url(@post) %>" data-width="600" data-numposts="5"></div>
  </div>

  <script type="text/javascript">
      <!--
      likeCount('fb_count_<%= @post.id %>', '<%= post_url(@post) %>');
      // tweetCount('tweet_count_<%= @post.id %>', '<%= post_url(@post) %>');
      hatebuCount('hatebu_count_<%= @post.id %>', '<%= post_url(@post) %>');
      // -->
  </script>

</div><!-- each_post -->